title: Jaswanth Reddy Devalapalle
description: "I am project engineer in wipro technologies.My skill set is React, javascript, typescript, html,css,java core ,oracle sql. I work in a timely manner by setting up time and priority for
tasks. I have an enthusiastic personality . I feel learning should happen everyday."
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
